name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Ninja
      uses: ashutoshvarma/setup-ninja@v1.1

    - name: CMake
      run: |
        cmake -GNinja .

    - name: Build
      run: |
        ninja

    - name: Test
      run: |
        ./demumble_test.py 
